### PR TITLE
Updating README to include qt5 specification

### PR DESCRIPTION
**Pull request by Winter-Guerra**
This is required for the build of BLDC-Tool. Otherwise, lots of errors occur.

### CODE REVIEW

**Comment by TimGremalm** [comment]
I don't think `sudo` is required to run BLDC-tool, and you should avoid using sudo when it's not necessary.
Just make sure your user is a member of dialout so BLDC-tool have the right to open a serial connection.
I think you should edit your pullrequest and remove sudo. Add something like this instead:
`sudo adduser $USER dialout`

**Comment by TimGremalm** [comment]
And +1 on the syntax highlighting.

**Comment by Winter-Guerra** [comment]
@TimGremalm Thanks for the pointer! I've updated the README to show how to access the serial port without sudo. Note that the restart is required, else the serial port still has access permission errors in Ubuntu 16.04LTS.

**Comment by Winter-Guerra** [comment]
@TimGremalm PING

**Comment by TimGremalm** [comment]
I'm guessing you want it merged. I think only @vedderb can push to this repo.
The changes looks good. :)

**Pull request merged**
